spring.application.name=certificate-genrator
spring.datasource.url=jdbc:postgresql://localhost:5432/certificatedb
spring.datasource.username=postgres
spring.datasource.password=Arora@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.security=DEBUG